/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	secretsyncv1alpha1 "sigs.k8s.io/secrets-store-sync-controller/api/secretsync/v1alpha1"
)

// SecretSyncLister helps list SecretSyncs.
// All objects returned here must be treated as read-only.
type SecretSyncLister interface {
	// List lists all SecretSyncs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*secretsyncv1alpha1.SecretSync, err error)
	// SecretSyncs returns an object that can list and get SecretSyncs.
	SecretSyncs(namespace string) SecretSyncNamespaceLister
	SecretSyncListerExpansion
}

// secretSyncLister implements the SecretSyncLister interface.
type secretSyncLister struct {
	listers.ResourceIndexer[*secretsyncv1alpha1.SecretSync]
}

// NewSecretSyncLister returns a new SecretSyncLister.
func NewSecretSyncLister(indexer cache.Indexer) SecretSyncLister {
	return &secretSyncLister{listers.New[*secretsyncv1alpha1.SecretSync](indexer, secretsyncv1alpha1.Resource("secretsync"))}
}

// SecretSyncs returns an object that can list and get SecretSyncs.
func (s *secretSyncLister) SecretSyncs(namespace string) SecretSyncNamespaceLister {
	return secretSyncNamespaceLister{listers.NewNamespaced[*secretsyncv1alpha1.SecretSync](s.ResourceIndexer, namespace)}
}

// SecretSyncNamespaceLister helps list and get SecretSyncs.
// All objects returned here must be treated as read-only.
type SecretSyncNamespaceLister interface {
	// List lists all SecretSyncs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*secretsyncv1alpha1.SecretSync, err error)
	// Get retrieves the SecretSync from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*secretsyncv1alpha1.SecretSync, error)
	SecretSyncNamespaceListerExpansion
}

// secretSyncNamespaceLister implements the SecretSyncNamespaceLister
// interface.
type secretSyncNamespaceLister struct {
	listers.ResourceIndexer[*secretsyncv1alpha1.SecretSync]
}
