apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secret-sync-controller
    app.kubernetes.io/part-of: secret-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: ssc-manager
  namespace: system
