apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: e2e-providerspc
spec:
  provider: e2e-provider
  parameters:
    objects: |
      array:
        - |
          objectName: foo
          objectVersion: v1
