{{- if .Values.validatingAdmissionPolicies.applyPolicies -}}
{{ include "secret-sync-controller.admissionApiVersion" . }}
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "secret-sync-controller-create-update-token-deny-policy-binding"
spec:
  policyName: "secret-sync-controller-create-update-token-deny-policy"
  validationActions: [Deny]
{{- end -}}
