{{- if .Values.validatingAdmissionPolicies.applyPolicies -}}
{{ include "secret-sync-controller.admissionApiVersion" . }}
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "secret-sync-controller-update-owners-check-oldobject-policy-binding"
spec:
  policyName: "secret-sync-controller-update-owners-check-oldobject-policy"
  validationActions: [Deny]
{{- end -}}
