{{- if .Values.validatingAdmissionPolicies.applyPolicies -}}
{{ include "secret-sync-controller.admissionApiVersion" . }}
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "secret-sync-controller-validate-annotation-policy-binding"
spec:
  policyName: "secret-sync-controller-validate-annotation-policy"
  validationActions: [Deny]
{{- end -}}
