/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apisecretsyncv1alpha1 "sigs.k8s.io/secrets-store-sync-controller/api/secretsync/v1alpha1"
	versioned "sigs.k8s.io/secrets-store-sync-controller/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/secrets-store-sync-controller/client/informers/externalversions/internalinterfaces"
	secretsyncv1alpha1 "sigs.k8s.io/secrets-store-sync-controller/client/listers/secretsync/v1alpha1"
)

// SecretSyncInformer provides access to a shared informer and lister for
// SecretSyncs.
type SecretSyncInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() secretsyncv1alpha1.SecretSyncLister
}

type secretSyncInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSecretSyncInformer constructs a new informer for SecretSync type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSecretSyncInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSecretSyncInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSecretSyncInformer constructs a new informer for SecretSync type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSecretSyncInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretSyncV1alpha1().SecretSyncs(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretSyncV1alpha1().SecretSyncs(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretSyncV1alpha1().SecretSyncs(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretSyncV1alpha1().SecretSyncs(namespace).Watch(ctx, options)
			},
		},
		&apisecretsyncv1alpha1.SecretSync{},
		resyncPeriod,
		indexers,
	)
}

func (f *secretSyncInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSecretSyncInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *secretSyncInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisecretsyncv1alpha1.SecretSync{}, f.defaultInformer)
}

func (f *secretSyncInformer) Lister() secretsyncv1alpha1.SecretSyncLister {
	return secretsyncv1alpha1.NewSecretSyncLister(f.Informer().GetIndexer())
}
