{{- if .Values.validatingAdmissionPolicies.applyPolicies -}}
{{ include "secrets-store-sync-controller.admissionApiVersion" . }}
kind: ValidatingAdmissionPolicy
metadata:
  name: "secrets-store-sync-controller-delete-policy"
spec:
  failurePolicy: Fail
  matchConditions:
    - name: 'user-is-secrets-store-sync-controller'
      expression: {{ include "chartname.matchConditionExpression" . | quote }}
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["DELETE"]
      resources:   ["secrets"]
  validations:
  - expression: "request.operation == 'delete'"
    message: "The controller is not allowed to delete secrets."
    messageExpression: "'secrets-store-sync-controller has failed to ' +  string(request.operation) + ' secrets in the ' + string(request.namespace) + ' namespace. The controller is not allowed to delete secrets.'"
{{- end -}}
