{{- if .Values.validatingAdmissionPolicies.applyPolicies -}}
{{ include "secrets-store-sync-controller.admissionApiVersion" . }}
kind: ValidatingAdmissionPolicy
metadata:
  name: "secrets-store-sync-controller-update-label-policy"
spec:
  failurePolicy: Fail
  matchConditions:
    - name: 'user-is-secrets-store-sync-controller'
      expression: {{ include "chartname.matchConditionExpression" . | quote }}
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["UPDATE"]
      resources:   ["secrets"]
  variables:
  - name: oldSecretHasLabels
    expression: "has(oldObject.metadata.labels) ? true : false"
  - name: oldSecretHasExpectedLabelKey
    expression: {{ include "secrets-store-sync-controller.oldSecretHasExpectedLabelKey" . | quote }}
  - name: oldSecretHasExpectedLabelValue
    expression: {{ include "secrets-store-sync-controller.oldSecretHasExpectedLabelValue" . | quote }}
  validations:
  - expression: "variables.oldSecretHasExpectedLabelKey && variables.oldSecretHasExpectedLabelValue"
    message: "Only secrets with the correct label can be updated"
    messageExpression: "'secrets-store-sync-controller has failed to ' +  string(request.operation) + ' secret with ' + string(object.type) + ' type ' + 'in the ' + string(request.namespace) + ' namespace because it does not have the correct label. Delete the secret and force the controller to recreate it with the correct label.'"
{{- end -}}
