{{- if .Values.validatingAdmissionPolicies.applyPolicies -}}
{{ include "secrets-store-sync-controller.admissionApiVersion" . }}
kind: ValidatingAdmissionPolicy
metadata:
  name: "secrets-store-sync-controller-validate-token-policy"
spec:
  failurePolicy: Fail
  matchConditions:
    - name: 'user-is-secrets-store-sync-controller'
      expression: {{ include "chartname.matchConditionExpression" . | quote }}
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE"]
      resources:   ["serviceaccounts/token"]
  variables:
  - name: audiencesList
    expression: {{ include "secrets-store-sync-controller.audiencesToList" . | quote }}
  - name: expirationSeconds
    expression: "string(object.spec.expirationSeconds) == '600'"
  - name: requestHasOnlyOneAudience
    expression: "object.spec.audiences.size() == 1"
  validations:
  - expression: "variables.expirationSeconds == true && variables.requestHasOnlyOneAudience == true && object.spec.audiences.all(aud, aud in variables.audiencesList)"
    message: "'Creating a serviceaccount token unauthorized.'"
    messageExpression: "'Unauthorized ServiceAccount token request in namespace ' + string(request.namespace) + ': the request must set expirationSeconds=600 and pick a single audience from [' + variables.audiencesList.join(', ') + ']'"
    reason: "Forbidden"
{{- end -}}
