{{- if .Values.validatingAdmissionPolicies.applyPolicies -}}
{{ include "secrets-store-sync-controller.admissionApiVersion" . }}
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "secrets-store-sync-controller-validate-annotation-policy-binding"
spec:
  policyName: "secrets-store-sync-controller-validate-annotation-policy"
  validationActions: [Deny]
{{- end -}}
