/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	secretsyncv1alpha1 "sigs.k8s.io/secrets-store-sync-controller/api/secretsync/v1alpha1"
	scheme "sigs.k8s.io/secrets-store-sync-controller/client/clientset/versioned/scheme"
)

// SecretSyncsGetter has a method to return a SecretSyncInterface.
// A group's client should implement this interface.
type SecretSyncsGetter interface {
	SecretSyncs(namespace string) SecretSyncInterface
}

// SecretSyncInterface has methods to work with SecretSync resources.
type SecretSyncInterface interface {
	Create(ctx context.Context, secretSync *secretsyncv1alpha1.SecretSync, opts v1.CreateOptions) (*secretsyncv1alpha1.SecretSync, error)
	Update(ctx context.Context, secretSync *secretsyncv1alpha1.SecretSync, opts v1.UpdateOptions) (*secretsyncv1alpha1.SecretSync, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, secretSync *secretsyncv1alpha1.SecretSync, opts v1.UpdateOptions) (*secretsyncv1alpha1.SecretSync, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*secretsyncv1alpha1.SecretSync, error)
	List(ctx context.Context, opts v1.ListOptions) (*secretsyncv1alpha1.SecretSyncList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *secretsyncv1alpha1.SecretSync, err error)
	SecretSyncExpansion
}

// secretSyncs implements SecretSyncInterface
type secretSyncs struct {
	*gentype.ClientWithList[*secretsyncv1alpha1.SecretSync, *secretsyncv1alpha1.SecretSyncList]
}

// newSecretSyncs returns a SecretSyncs
func newSecretSyncs(c *SecretSyncV1alpha1Client, namespace string) *secretSyncs {
	return &secretSyncs{
		gentype.NewClientWithList[*secretsyncv1alpha1.SecretSync, *secretsyncv1alpha1.SecretSyncList](
			"secretsyncs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *secretsyncv1alpha1.SecretSync { return &secretsyncv1alpha1.SecretSync{} },
			func() *secretsyncv1alpha1.SecretSyncList { return &secretsyncv1alpha1.SecretSyncList{} },
		),
	}
}
