name: E2E Provider Tests

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Registry for pulling images'
        required: true
        default: 'us-central1-docker.pkg.dev/k8s-staging-images/secrets-store-sync'
      imageName:
        description: 'Secret Store Sync Controller image name'
        required: true
        default: 'controller'
      imageVersion:
        description: 'image version for Secret Store Sync Controller'
        required: true
        default: 'vCHANGE_ME'

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        KUBERNETES_VERSION: ["v1.32.11", "v1.33.7", "v1.34.3", "v1.35.1"]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: false
      - name: Setup helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
      - name: Setup Kubectl
        uses: azure/setup-kubectl@15650b3ad78fff148532a140b8a4c821796b2d7b # v5.0.0
      - name: Setup Kind
        uses: engineerd/setup-kind@ecfad61750951586a9ef973db567df1d28671bdc # v0.6.2
        with:
          version: "v0.31.0"
          image: "kindest/node:${{ matrix.KUBERNETES_VERSION }}"
          name: "kind-kube-${{ matrix.KUBERNETES_VERSION }}"
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: "^1.25"
      - name: Test
        run: |
          # GH action sets this var by default. We need to explicitly unset it so that build commit hash is not appended to image tag.
          unset CI

          make helm-manifest-install run-e2e-provider-tests
        env:
          REGISTRY: ${{ github.event.inputs.registry }}
          IMAGE_NAME: ${{ github.event.inputs.imageName }}
          IMAGE_VERSION: ${{ github.event.inputs.imageVersion }}
