name: "govulncheck"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 7 * * 1" # Mondays at 7:00 AM

permissions:
  contents: read

jobs:
  govulncheck:
    name: Dependency vulnerability check
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.0.0
        with:
          persist-credentials: false

      - name: Golang vulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4

      - name: Golang vulncheck - tools
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          work-dir: hack/tools
