name: "govulncheck"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 7 * * 1" # Mondays at 7:00 AM

permissions:
  contents: read

jobs:
  govulncheck:
    name: Dependency vulnerability check
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Golang vulncheck
        uses: golang/govulncheck-action@31f7c5463448f83528bd771c2d978d940080c9fd # v1.0.4
        with:
          repo-checkout: false

      - name: Golang vulncheck - tools
        uses: golang/govulncheck-action@31f7c5463448f83528bd771c2d978d940080c9fd # v1.0.4
        with:
          repo-checkout: false
          work-dir: hack/tools
