name: 'Ensure codegen works'
on: [pull_request]

permissions:
  contents: read

jobs:
  verify-codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "^1.25"
      - name: Run codegens
        run: |
          make generate
          make manifests
      - name: Verify git output
        shell: bash
        run: |
          cp ./config/crd/bases/secret-sync.x-k8s.io_secretsyncs.yaml ./manifest_staging/charts/secrets-store-sync-controller/crds/secret-sync.x-k8s.io_secretsyncs.yaml
          if [ -n "$(git status -s)" ]; then
            echo 'Detected code generation changes'
            echo 'Make sure to run `make generate` and `make manifests` and commit those changes'
            git diff
            exit 1
          fi
